//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadAndSaveExcelData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Excel_File
    {
        public int AutoId { get; set; }
        public string Category { get; set; }
        public string Functionality { get; set; }
        public string Description { get; set; }
        public string New { get; set; }
        public string HelpTopic { get; set; }
    }
}
